### ISSUE TITLE
errors on installation

### ISSUE THREAD

**Issue by bamboowonder** [archivist/archivist#153]
I'm trying to install this for our nonprofit org.  I get all the way along, but on "npm start" it then fails with the following.  I've been unable to figure out why it is failing.

ubuntu@do:~/archivist$ npm start

> substance-archivist@1.0.0 start /home/ubuntu/archivist
> foreman start

01:49:30 web.1  | started with pid 6005
01:49:30 web.1  | storing in cache...
01:49:30 web.1  | ### QUERY OPTIONS: {
01:49:30 web.1  |   "filters": null,
01:49:30 web.1  |   "published": true,
01:49:30 web.1  |   "entities": true
01:49:30 web.1  | }
01:49:31 web.1  | storing in cache...
01:49:31 web.1  | storing in cache...
01:49:31 web.1  | storing in cache...
01:49:31 web.1  | ### QUERY OPTIONS: {
01:49:31 web.1  |   "filters": null,
01:49:31 web.1  |   "entities": true,
01:49:31 web.1  |   "published": true
01:49:31 web.1  | }
01:49:31 web.1  | storing in cache...
01:49:31 web.1  | Started connection, waiting for it to open...
01:49:31 web.1  | fs.js:892
01:49:31 web.1  |   return binding.stat(pathModule._makeLong(path));
01:49:31 web.1  |                  ^
01:49:31 web.1  | 
01:49:31 web.1  | Error: ENOENT: no such file or directory, stat '/home/ubuntu/archivist/public/assets/img/favicon.png'
01:49:31 web.1  |     at Error (native)
01:49:31 web.1  |     at Object.fs.statSync (fs.js:892:18)
01:49:31 web.1  |     at favicon (/home/ubuntu/archivist/node_modules/serve-favicon/index.js:64:15)
01:49:31 web.1  |     at Object.<anonymous> (/home/ubuntu/archivist/server/index.js:60:9)
01:49:31 web.1  |     at Module._compile (module.js:413:34)
01:49:31 web.1  |     at Object.Module._extensions..js (module.js:422:10)
01:49:31 web.1  |     at Module.load (module.js:357:32)
01:49:31 web.1  |     at Function.Module._load (module.js:314:12)
01:49:31 web.1  |     at Function.Module.runMain (module.js:447:10)
01:49:31 web.1  |     at startup (node.js:148:18)
01:49:31 web.1  |     at node.js:405:3
01:49:32 web.1  | exited with code 1
01:49:32 system | sending SIGTERM to all processes

npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! substance-archivist@1.0.0 start: `foreman start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the substance-archivist@1.0.0 start script 'foreman start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the substance-archivist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     foreman start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs substance-archivist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls substance-archivist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/archivist/npm-debug.log

==================================================
and here is the contents of the /home/ubuntu/archivist/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.8.7
3 info using node@v5.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle substance-archivist@1.0.0~prestart: substance-archivist@1.0.0
6 silly lifecycle substance-archivist@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle substance-archivist@1.0.0~start: substance-archivist@1.0.0
8 verbose lifecycle substance-archivist@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle substance-archivist@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/archivist/node_modules/.bin:/usr/bin:/home/ubuntu/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle substance-archivist@1.0.0~start: CWD: /home/ubuntu/archivist
11 silly lifecycle substance-archivist@1.0.0~start: Args: [ '-c', 'foreman start' ]
12 silly lifecycle substance-archivist@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle substance-archivist@1.0.0~start: Failed to exec start script
14 verbose stack Error: substance-archivist@1.0.0 start: `foreman start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:244:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid substance-archivist@1.0.0
16 verbose cwd /home/ubuntu/archivist
17 error Linux 3.13.0-85-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v5.11.0
20 error npm  v3.8.7
21 error code ELIFECYCLE
22 error substance-archivist@1.0.0 start: `foreman start`
22 error Exit status 1
23 error Failed at the substance-archivist@1.0.0 start script 'foreman start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the substance-archivist package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     foreman start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs substance-archivist
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls substance-archivist
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
/home/ubuntu/archivist/npm-debug.log (END)

**Comment by michael** [comment]
Thanks for reporting. @Integral can this be made robust regarding missing files (favicon,...) in the public folder?

**Comment by Integral** [comment]
Hello!
Looks like postinstall script didn't executed. Try to run gulp in console and then npm start again.

**Comment by bamboowonder** [comment]
Hello!

I must be doing something wrong, it does not look like gulp is installed?  I tried to npm install it but no dice.  Here is the console output.
```

ubuntu@do:~/archivist$ npm install --save gulp-install
substance-archivist@1.0.0 /home/ubuntu/archivist
└── gulp-install@0.6.0 

npm WARN substance-archivist@1.0.0 No repository field.
npm WARN substance-archivist@1.0.0 No license field.
ubuntu@do:~/archivist$ npm gulp gulpfile.js 

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, logout, ls, outdated, owner, pack, ping, prefix,
    prune, publish, rb, rebuild, repo, restart, root,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/ubuntu/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.8.7 /usr/lib/node_modules/npm
ubuntu@do:~/archivist$ gulp
No command 'gulp' found, did you mean:
 Command 'gslp' from package 'ghostscript' (main)
gulp: command not found
ubuntu@do:~/archivist$ 

```

**Comment by Integral** [comment]
Hey, looks like you didn't install all modules
pls do ```rm -rf node_modules```
and try ```sudo npm install```

**Comment by bamboowonder** [comment]
hmm.  I ran both those commands inside the archivist directory.
then ran: gulp
but it said it isn't installed.
and the same errors when i do: npm start

I installed the nodejs ver 5x.  Does your system rely on ver 4x?

On a side note, do you have a demo server or image I could use instead?  My main reason for installing is to see if the other people here would like to use this system for our transcription archives.  So I really just need to create a demo for them (and me).

Thank you,

**Comment by Integral** [comment]
it's very strange as we have gulp as dependency here: https://github.com/archivist/archivist/blob/master/package.json
i didn't try with node 5, but at the same time i see no reason why it shouldn't work...
we have kind of demo server, but it's private and filled with documents in russian...
we have two options here:
- i could look at your server an investigate a bit
- i could give you access for some time to our demo server
for both options i would like to get a bit more information from you, like what kind of nonprofit organization and what do you want to do :) you could write to me beilinson@gmail.com, thanks

**Comment by bamboowonder** [comment]
Hi Daniel,

I just sent you an email.

Thanks,

David
